# Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gerador-videos
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "1"
        run.googleapis.com/timeout: "300s"
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/PROJECT_ID/gerador-videos:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DEBUG
          value: "False"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: app-secrets
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: app-secrets
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: STRIPE_SECRET_KEY
              name: app-secrets
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              key: STRIPE_PUBLISHABLE_KEY
              name: app-secrets
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: STRIPE_WEBHOOK_SECRET
              name: app-secrets
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              key: EMAIL_HOST_USER
              name: app-secrets
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: EMAIL_HOST_PASSWORD
              name: app-secrets
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: app-secrets
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: app-secrets
        - name: AWS_STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: AWS_STORAGE_BUCKET_NAME
              name: app-secrets
        - name: AWS_S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              key: AWS_S3_ENDPOINT_URL
              name: app-secrets
        - name: CLOUDFLARE_R2_PUBLIC_URL
          valueFrom:
            secretKeyRef:
              key: CLOUDFLARE_R2_PUBLIC_URL
              name: app-secrets
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: GOOGLE_CLOUD_REGION
          value: "us-central1"
        - name: CLOUD_RUN_URL
          value: "https://gerador-videos-PROJECT_ID.a.run.app"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3