version: '3.8'

services:
  # 1. O Site (Backend Django)
  # Este serviço permite que você acesse o painel pelo IP 192.168.0.2:8000
  web:
    build: .
    container_name: gerador_videos_web
    restart: always
    # Bind 0.0.0.0 permite acesso externo (pelo IP da rede)
    command: gunicorn gerador_videos.wsgi:application --bind "0.0.0.0:8000" --timeout 3600
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Conexão direta com o Redis na Nuvem (Upstash)
      - CELERY_BROKER_URL=rediss://default:Aeo7AAIncDE2NThhZWNjMDEwOTM0YTY3OTg0MjdmYjhmMDBlMWI4Y3AxNTk5NjM@sweet-gull-59963.upstash.io:6379

  # 2. O Trabalhador (Gera os vídeos)
  # Este é o serviço que usa a força do PC para criar o vídeo
  celery_worker:
    build: .
    container_name: lunderon_worker
    restart: always
    # Alterado para --pool=solo para garantir estabilidade no processamento de IA
    command: celery -A gerador_videos worker -l info --pool=solo
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # Conexão direta com o Redis na Nuvem (Upstash)
      - CELERY_BROKER_URL=rediss://default:Aeo7AAIncDE2NThhZWNjMDEwOTM0YTY3OTg0MjdmYjhmMDBlMWI4Y3AxNTk5NjM@sweet-gull-59963.upstash.io:6379
    depends_on:
      - web

  # 3. O Agendador (Limpeza automática)
  # Limpa arquivos do R2 a cada hora
  celery_beat:
    build: .
    container_name: lunderon_beat
    restart: always
    command: celery -A gerador_videos beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # Conexão direta com o Redis na Nuvem (Upstash)
      - CELERY_BROKER_URL=rediss://default:Aeo7AAIncDE2NThhZWNjMDEwOTM0YTY3OTg0MjdmYjhmMDBlMWI4Y3AxNTk5NjM@sweet-gull-59963.upstash.io:6379
    depends_on:
      - web