# Generated by Django 5.2.5 on 2025-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicabase',
            name='arquivo_musica',
            field=models.FileField(blank=True, null=True, upload_to='musicas_base/'),
        ),
        migrations.AlterField(
            model_name='videobase',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, upload_to='videos_base/'),
        ),
    ]
