# Generated by Django 5.2.5 on 2025-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_musicabase_arquivo_musica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogerado',
            name='legenda_sincronizada',
        ),
        migrations.RemoveField(
            model_name='videogerado',
            name='narrador_texto',
        ),
        migrations.RemoveField(
            model_name='videogerado',
            name='narrador_tom',
        ),
        migrations.RemoveField(
            model_name='videogerado',
            name='narrador_velocidade',
        ),
        migrations.RemoveField(
            model_name='videogerado',
            name='narrador_voz',
        ),
        migrations.AddField(
            model_name='videogerado',
            name='imagem_upload',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_upload/'),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='tipo_geracao',
            field=models.CharField(choices=[('imagem', 'Imagem para Vídeo'), ('texto', 'Texto para Vídeo')], default='texto', max_length=10),
        ),
    ]
