# Generated by Django 5.2.5 on 2025-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_videogerado_legenda_sincronizada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogerado',
            name='imagem_upload',
        ),
        migrations.RemoveField(
            model_name='videogerado',
            name='tipo_geracao',
        ),
        migrations.AddField(
            model_name='videogerado',
            name='legenda_sincronizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='narrador_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='narrador_tom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='narrador_velocidade',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='narrador_voz',
            field=models.CharField(default='pt-BR-Wavenet-B', max_length=50),
        ),
    ]
