# Generated by Django 5.2.5 on 2025-09-04 05:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_videogerado_imagem_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicabase',
            name='musica_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videobase',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicabase',
            name='arquivo_musica',
            field=models.FileField(blank=True, null=True, storage=core.models.MediaStorage(), upload_to='musicas_base/'),
        ),
        migrations.AlterField(
            model_name='videobase',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, storage=core.models.MediaStorage(), upload_to='videos_base/'),
        ),
    ]
