# Generated by Django 5.2.5 on 2025-09-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_musicabase_musica_url_videobase_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicabase',
            name='musica_url',
        ),
        migrations.RemoveField(
            model_name='videobase',
            name='video_url',
        ),
        migrations.AddField(
            model_name='musicabase',
            name='object_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videobase',
            name='object_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
