# Generated by Django 5.2.5 on 2025-09-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_musicabase_musica_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamusica',
            name='pasta',
            field=models.CharField(blank=True, help_text='Nome da pasta no Cloudflare R2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoriavideo',
            name='pasta',
            field=models.CharField(blank=True, help_text='Nome da pasta no Cloudflare R2', max_length=100, null=True),
        ),
    ]
