# Generated by Django 5.2.5 on 2025-09-09 18:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_categoriamusica_pasta_categoriavideo_pasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='tipo_fonte_video',
            field=models.CharField(choices=[('base', 'Vídeo da Base'), ('url', 'URL Externa'), ('upload', 'Upload Direto')], default='base', max_length=10),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='url_video_vendedor',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Vídeo do Vendedor'),
        ),
        migrations.AlterField(
            model_name='musicabase',
            name='arquivo_musica',
            field=models.FileField(blank=True, null=True, storage=core.models.MediaStorage(), upload_to=core.models.upload_musica_para_categoria),
        ),
        migrations.AlterField(
            model_name='videobase',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, storage=core.models.MediaStorage(), upload_to=core.models.upload_video_para_categoria),
        ),
    ]
