# Generated by Django 5.2.5 on 2025-09-09 22:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_categoriamusica_pasta_categoriavideo_pasta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicabase",
            name="arquivo_musica",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.MediaStorage(),
                upload_to=core.models.upload_musica_para_categoria,
            ),
        ),
        migrations.AlterField(
            model_name="videobase",
            name="arquivo_video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.MediaStorage(),
                upload_to=core.models.upload_video_para_categoria,
            ),
        ),
    ]
