# Generated by Django 5.2.5 on 2025-09-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_musicabase_arquivo_musica_and_more'),
        ('core', '0018_videogerado_tipo_fonte_video_and_more'),
    ]

    operations = [
    ]
