# Generated by Django 5.2.5 on 2025-09-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_videogerado_tipo_fonte_video_and_more'),
    ]

    operations = [
    ]
