# Generated by Django 5.2.5 on 2025-09-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_videogerado_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogerado",
            name="caminho_audio_narrador",
            field=models.CharField(
                blank=True,
                help_text="Caminho do áudio de narração gerado",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="videogerado",
            name="caminho_imagem_texto",
            field=models.CharField(
                blank=True,
                help_text="Caminho da imagem de texto gerada",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="videogerado",
            name="caminho_legenda_ass",
            field=models.CharField(
                blank=True,
                help_text="Caminho da legenda ASS gerada",
                max_length=500,
                null=True,
            ),
        ),
    ]
