# Generated by Django 5.2.5 on 2025-09-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_videogerado_caminho_audio_narrador_and_more"),
    ]

    operations = []
