# Generated by Django 5.2.5 on 2025-09-13 20:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20250910_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="limite_testes_gratis",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="usuario",
            name="logomarca",
            field=models.ImageField(
                blank=True,
                help_text="Logomarca para adicionar na tela final dos vídeos",
                null=True,
                storage=core.models.MediaStorage(),
                upload_to="logomarcas_usuarios/",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="posicao_logomarca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("superior_esquerdo", "Superior Esquerdo"),
                    ("superior_direito", "Superior Direito"),
                    ("inferior_esquerdo", "Inferior Esquerdo"),
                    ("inferior_direito", "Inferior Direito"),
                    ("centro", "Centro"),
                ],
                default="inferior_direito",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="testes_gratis_utilizados",
            field=models.IntegerField(default=0),
        ),
    ]
