# Generated by Django 5.2.5 on 2025-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_usuario_limite_testes_gratis_usuario_logomarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
