# Generated by Django 5.2.5 on 2025-09-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usuario_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
