# Generated by Django 5.2.5 on 2025-09-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_usuario_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='limite_testes_gratis',
        ),
    ]
