# Generated by Django 5.2.5 on 2025-09-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('core', '0028_remove_usuario_limite_testes_gratis'),
    ]

    operations = [
    ]
