# Generated by Django 5.2.5 on 2025-09-15 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_usuario_limite_testes_gratis"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorteGerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url_original", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="PROCESSANDO",
                        max_length=20,
                    ),
                ),
                (
                    "arquivo_final",
                    models.CharField(
                        blank=True,
                        help_text="Caminho do corte gerado no Cloudflare R2",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
