# Generated by Django 5.2.5 on 2025-09-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_cortegerado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cortegerado",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSANDO", "Processando"),
                    ("CONCLUIDO", "Concluído"),
                    ("ERRO", "Erro"),
                    ("MANUAL", "Aguardando Corte Manual"),
                ],
                default="PROCESSANDO",
                max_length=20,
            ),
        ),
    ]
