# Generated by Django 5.2.5 on 2025-09-17 13:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20250917_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marcar este plano como destaque na página de preços'),
        ),
        migrations.AddField(
            model_name='plano',
            name='qualidade_video',
            field=models.CharField(default='720p', help_text='Qualidade máxima do vídeo (ex: 720p, 1080p)', max_length=20),
        ),
        migrations.AddField(
            model_name='plano',
            name='sem_marca_dagua',
            field=models.BooleanField(default=False, help_text="Remove a marca d'água dos vídeos"),
        ),
        migrations.AddField(
            model_name='plano',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID do Preço no Stripe', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='suporte_prioritario',
            field=models.BooleanField(default=False, help_text='Acesso a suporte prioritário'),
        ),
        migrations.AddField(
            model_name='plano',
            name='videos_por_mes',
            field=models.IntegerField(default=10, help_text='Número de vídeos permitidos por mês'),
        ),
        migrations.AlterField(
            model_name='musicabase',
            name='arquivo_musica',
            field=models.FileField(blank=True, null=True, storage=core.models.MediaStorage(), upload_to=core.models.upload_musica_para_categoria),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logomarca',
            field=models.ImageField(blank=True, help_text='Logomarca para adicionar na tela final dos vídeos', null=True, storage=core.models.MediaStorage(), upload_to='logomarcas_usuarios/'),
        ),
        migrations.AlterField(
            model_name='videobase',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, storage=core.models.MediaStorage(), upload_to=core.models.upload_video_para_categoria),
        ),
        # migrations.DeleteModel(
        #     name='VideoCorte',
        # ),
    ]
