# Generated by Django 5.2.5 on 2025-09-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_plano_destaque_plano_qualidade_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCorte',
        ),
    ]
