# Generated by Django 5.2.5 on 2025-09-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("core", "0030_alter_cortegerado_status"),
    ]

    operations = []
