# Generated by Django 5.2.5 on 2025-09-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20250917_0228'),
    ]

    operations = [
        # Migration operations removed - fields already removed from model
        # This migration is kept as a placeholder to maintain migration sequence
    ]
