# Generated by Django 5.2.5 on 2025-09-16 20:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_merge_0002_initial_0030_alter_cortegerado_status"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="videocorte",
        #     name="usuario",
        # ),  # Commented out - model already deleted in migration 0031
        migrations.AlterField(
            model_name="musicabase",
            name="arquivo_musica",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.MediaStorage(),
                upload_to=core.models.upload_musica_para_categoria,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="logomarca",
            field=models.ImageField(
                blank=True,
                help_text="Logomarca para adicionar na tela final dos vídeos",
                null=True,
                storage=core.models.MediaStorage(),
                upload_to="logomarcas_usuarios/",
            ),
        ),
        migrations.AlterField(
            model_name="videobase",
            name="arquivo_video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.MediaStorage(),
                upload_to=core.models.upload_video_para_categoria,
            ),
        ),
        migrations.DeleteModel(
            name="CorteGerado",
        ),
        # migrations.DeleteModel(
        #     name="VideoCorte",
        # ),  # Commented out - model already deleted in migration 0031
    ]
