# Generated by Django 5.2.5 on 2025-09-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_musicabase_arquivo_musica_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='VideoCorte',
        # ),  # Model already deleted, commented out to avoid errors
    ]
