# Generated by Django 5.2.5 on 2025-09-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_videocorte'),
        ('core', '0034_delete_videocorte'),
    ]

    operations = [
    ]
