# Generated by Django 5.2.5 on 2025-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_0031_delete_videocorte_0034_delete_videocorte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='destaque',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='qualidade_video',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='sem_marca_dagua',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='suporte_prioritario',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='videos_por_mes',
        ),
        migrations.AlterField(
            model_name='categoriamusica',
            name='pasta',
            field=models.CharField(blank=True, help_text='Nome da pasta no Cloudflare R2 (gerado automaticamente se deixado em branco).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoriavideo',
            name='pasta',
            field=models.CharField(blank=True, help_text='Nome da pasta no Cloudflare R2 (gerado automaticamente se deixado em branco).', max_length=100, null=True),
        ),
    ]
