# Generated by Django 5.2.5 on 2025-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_plano_destaque_remove_plano_qualidade_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='limite_videos_mensal',
            field=models.IntegerField(default=30, help_text='Quantos vídeos o assinante deste plano pode gerar por mês.'),
        ),
        migrations.AddField(
            model_name='plano',
            name='link_pdf_dicas',
            field=models.URLField(blank=True, help_text='Link para o PDF de dicas (apenas para o plano Pro).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID do Preço deste plano no Stripe (ex: price_123abc...)', max_length=255, null=True),
        ),
    ]
