# Generated by Django 5.2.5 on 2025-09-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_videocorte_usuario_and_more"),
        ("core", "0037_plano_limite_videos_mensal_plano_link_pdf_dicas_and_more"),
    ]

    operations = []
