# Generated by Django 5.2.5 on 2025-09-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20250921_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogerado',
            name='duracao_segundos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
