# Generated by Django 5.2.5 on 2025-09-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_videogerado_notificacao_vista"),
        ("core", "0039_alter_videogerado_duracao_segundos"),
    ]

    operations = []
