# Generated by Django 4.2.4 on 2025-09-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_videogerado_duracao_segundos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogerado',
            name='status',
            field=models.CharField(default='PROCESSANDO', max_length=50),
        ),
    ]
