# Generated by Django 4.2.5 on 2025-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_videogerado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='mensagem_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='notificacao_vista',
            field=models.BooleanField(default=True),
        ),
    ]
