# Generated by Django 5.2.5 on 2025-09-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_merge_20250927_1408"),
        ("core", "0041_add_notification_fields"),
    ]

    operations = []
