# Generated by Django 5.2.5 on 2025-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_merge_20250928_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videogerado",
            name="notificacao_vista",
            field=models.BooleanField(default=True),
        ),
    ]
