# Generated by Django 5.2.5 on 2025-10-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_videogerado_notificacao_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='thumbnail_key',
            field=models.CharField(blank=True, help_text='Caminho da thumbnail do vídeo no R2', max_length=500, null=True),
        ),
    ]
