# Generated by Django 5.2.5 on 2025-10-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_videogerado_thumbnail_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteGerado',
            fields=[
                ('video_gerado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.videogerado')),
                ('youtube_url', models.URLField(max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
            ],
        ),
    ]
